kernel.config:
  charset:             UTF-8
  error_handler_level: null

web.web: ~

web.templating:
  escaping:       htmlspecialchars
  assets_version: SomeVersionScheme

doctrine.dbal:
  dbname:   xxxxxxxx
  username: root
  password: ~

doctrine.orm: ~

swift.mailer:
  transport: gmail
  username:  xxxxxxxx
  password:  xxxxxxxx
